### ISSUE TITLE
JavaScript error at launch on macOS

### ISSUE THREAD

**Issue by kawaiier** [Toinane/colorpicker#117]
Just updated from 2.0.3 to 2.0.5 on macOS and keep getting this error on every startup. The app works as intended, though.

**A JavaScript error occurred in the main process**
`Uncaught Exception:
SyntaxError: Unexpected token u in JSON at position 0
at JSON.parse (<anonymous>)
at Request._callback (/Applications/Colorpicker.app/Contents/Resources/app.asar/src/checkUpdate.js:18:31)
at self.callback (/Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/request/request.js:185:22)
at Request.emit (events.js:223:5)
at Request.onRequestError (/Applications/Colorpicker.app/Contents/Resources/app.asar/node_modules/request/request.js:877:8)
at ClientRequest.emit (events.js:223:5)
at TLSSocket.socketErrorListener (_http_client.js:406:9)
at TLSSocket.emit (events.js:223:5)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)`

**Comment by Toinane** [comment]
hey @kawaiier sorry for my really late response,
The storage file is corrupted, you have to delete it manualy

To found the file colorpicker.json file, you have to go :

Mac OS: ~/Library/Application Support/colorpicker/storage/
Windows: C:\Users\AppData\Roaming\Colorpicker\storage
Linux: ~/.config/colorpicker/storage

Delete it and relaunch the app, it will work again!

I'll make a fix later to not show again this issue
