### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by h2appy** [Toinane/colorpicker#31]
My environment:
macOS: 10.13.6
nodejs: 10.10.0

and the error is:

johnny@localhost:~/colorpicker-master$ yarn release
yarn run v1.9.4
$ build --publish=never --config colorpicker-build.json
  • electron-builder version=20.0.8
  • loaded configuration file=/Users/liq/Downloads/colorpicker-master/colorpicker-build.json
  • writing effective config file=out/electron-builder.yaml
  • rebuilding native production dependencies platform=darwin arch=x64
  • rebuilding native dependency name=osx-mouse
  • rebuilding native dependency name=robotjs
  • packaging       platform=darwin arch=x64 electron=1.8.4 appOutDir=out/mac
Downloading tmp-13193-1-SHASUMS256.txt-1.8.4
[============================================>] 100.0% of 3.43 kB (3.43 kB/s)
  • skipped macOS application code signing reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, see https://electron.build/code-signing allIdentities=
                                               1) 8575B27EE6CC2A75A4C19B2904335AC3094F4FCA "com.apple.idms.appleid.prd.7547466d49716370776f4e2b6f456a417454645776413d3d" (CSSMERR_TP_CERT_EXPIRED)
                                               2) 1F22E5B1071FA0CDBFCF02E0C095C74FC792386B "iPhone Developer: qiang li (YU5Z5XFL59)" (CSSMERR_TP_CERT_EXPIRED)
                                               3) BBBD8D8B01985395E381EB13424040B67EB58F0E "iPhone Distribution: Beijing Medvision Information Technology Co., Ltd. (87GLMWCJKE)" (CSSMERR_TP_CERT_EXPIRED)
                                               4) ECF4629D347D69D65622081F40F9BEB472B91ECC "iPhone Developer: lq@mmedi.cn (8FV3CZCCVY)" (CSSMERR_TP_CERT_EXPIRED)
                                               5) B43EECB44228516DB607B1ACD93B6B826CBEA9D2 "com.apple.idms.appleid.prd.7547466d49716370776f4e2b6f456a417454645776413d3d" (CSSMERR_TP_CERT_EXPIRED)
                                               6) 339F31E90DB580552B48953EEB43588F01727EDB "com.apple.systemdefault" (CSSMERR_TP_NOT_TRUSTED)
                                               7) C84DB4E1F3CAF8F8CDADEED61CB37A3049AD0516 "com.apple.kerberos.kdc" (CSSMERR_TP_NOT_TRUSTED)
                                                  7 identities found
                                             
                                               Valid identities only
                                                  0 valid identities found
  • building        target=macOS zip arch=x64 file=out/Colorpicker-2.0.1-mac.zip
  • building        target=DMG arch=x64 file=out/Colorpicker-2.0.1.dmg
Error: Cannot find module 'builder-util/out/license'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at _load_license (/Users/liq/Downloads/colorpicker-master/node_modules/dmg-builder/out/dmgLicense.js:87:23)
    at /Users/liq/Downloads/colorpicker-master/node_modules/dmg-builder/src/dmgLicense.ts:13:30
    at Generator.next (<anonymous>)
From previous event:
    at addLicenseToDmg (/Users/liq/Downloads/colorpicker-master/node_modules/dmg-builder/out/dmgLicense.js:74:21)
    at /Users/liq/Downloads/colorpicker-master/node_modules/dmg-builder/src/dmg.ts:58:31
    at Generator.next (<anonymous>)
From previous event:
    at DmgTarget.build (/Users/liq/Downloads/colorpicker-master/node_modules/dmg-builder/out/dmg.js:243:11)
    at taskManager.addTask.default.map.it (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/platformPackager.ts:121:67)
From previous event:
    at MacPackager.packageInDistributableFormat (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/platformPackager.ts:121:23)
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/macPackager.ts:95:26
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/macPackager.ts:95:10
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/out/macPackager.js:209:11)
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/packager.ts:372:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/liq/Downloads/colorpicker-master/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/liq/Downloads/colorpicker-master/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/out/packager.js:441:11)
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/packager.ts:316:52
    at Generator.next (<anonymous>)
    at /Users/liq/Downloads/colorpicker-master/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/liq/Downloads/colorpicker-master/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/out/packager.js:385:11)
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/packager.ts:278:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Packager.build (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/out/packager.js:341:11)
    at /Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/src/index.ts:50:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder-lib/out/index.js:47:21)
    at build (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder/src/builder.ts:228:10)
    at then (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Object.args [as handler] (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder/src/cli/cli.ts:48:33)
    at Object.runCommand (/Users/liq/Downloads/colorpicker-master/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/Users/liq/Downloads/colorpicker-master/node_modules/yargs/yargs.js:1074:24)
    at Object.get [as argv] (/Users/liq/Downloads/colorpicker-master/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/Users/liq/Downloads/colorpicker-master/node_modules/electron-builder/src/cli/cli.ts:42:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)

**Comment by h2appy** [comment]
It's OK if using electron-builder version=20.20.4

**Comment by Toinane** [comment]
Hey! Thank's for your issue, I will update this now!

**Comment by Toinane** [comment]
fix in 9ada5ef! thank you :)
Feel free to reopen if it's not work again
